services:
  # BACKEND (PHP Slim)
  api:
    build: ./forum-backend
    ports:
      - "8000:8080"
    environment:
      JWT_SECRET: "MeinSuperGeheimesPasswort123!"
    volumes:
      # Wir mounten den Ordner 'var' nach au√üen, damit die SQLite-DB persistent bleibt.
      # Host-Path muss ggf. auf Zielsystem angepasst werden.
      - ./forum-backend/var:/var/www/html/var

  # FRONTEND (React)
  web:
    build: ./forum-frontend
    ports:
      - "80:80"
    depends_on:
      - api
